### ISSUE TITLE
compiling failed

### ISSUE THREAD

**Issue by mamengjin** [isrc-cas/rvv-benchmark#1]
clang-12 error: invalid arch name 'rv64gcv'

**Comment by mamengjin** [comment]
mema@atx512server6:~/workstation/rvv/rvv-benchmark$ make
/home/mema/usr/local/riscvv09/llvm/bin/clang --target=riscv64-unknown-elf -march=rv64gcv --sysroot=/home/mema/usr/local/riscvv09/gnu/riscv64-unknown-e/home/mema/usr/local/riscvv09/gnu -o rvv-test main.c memcpy.s sgemm.S strlen.s vvaddint32.s saxpy.s strcpy.s strncpy.s
clang-12: error: invalid arch name 'rv64gcv', requires '-menable-experimental-extensions' for experimental extension 'v'
clang-12: error: invalid arch name 'rv64gcv', requires '-menable-experimental-extensions' for experimental extension 'v'
clang-12: error: invalid arch name 'rv64gcv', requires '-menable-experimental-extensions' for experimental extension 'v'
clang-12: error: invalid arch name 'rv64gcv', requires '-menable-experimental-extensions' for experimental extension 'v'
clang-12: error: invalid arch name 'rv64gcv', requires '-menable-experimental-extensions' for experimental extension 'v'
clang-12: error: invalid arch name 'rv64gcv', requires '-menable-experimental-extensions' for experimental extension 'v'
clang-12: error: invalid arch name 'rv64gcv', requires '-menable-experimental-extensions' for experimental extension 'v'
clang-12: error: invalid arch name 'rv64gcv', requires '-menable-experimental-extensions' for experimental extension 'v'
clang-12: error: invalid arch name 'rv64gcv', requires '-menable-experimental-extensions' for experimental extension 'v'
Makefile:23: recipe for target 'rvv-test' failed

**Comment by mamengjin** [comment]
mema@atx512server6:~/workstation/rvv/rvv-benchmark$ make
/home/mema/usr/local/riscvv09/llvm/bin/clang --target=riscv64-unknown-elf -march=rv64gc -menable-experimental-extensions --sysroot=/home/mema/usr/local/riscvv09/gnu/riscv64-unknown-elf --gcc-toolchain=/home/mema/usr/local/riscvv09/gnu -o rvv-test main.c memcpy.s sgemm.S strlen.s vvaddint32.s saxpy.s strcpy.s strncpy.s
clang-12: warning: argument unused during compilation: '-menable-experimental-extensions' [-Wunused-command-line-argument]
memcpy.s:10:5: error: instruction requires the following: 'V' (Vector Instructions)
    vsetvli t0, a2, e8,m8,ta,ma   # Vectors of 8b
    ^
memcpy.s:11:5: error: instruction requires the following: 'V' (Vector Instructions)
    vle8.v v0, (a1)               # Load bytes
    ^
memcpy.s:14:5: error: instruction requires the following: 'V' (Vector Instructions)
    vse8.v v0, (a3)               # Store bytes
    ^
sgemm.S:82:5: error: instruction requires the following: 'V' (Vector Instructions)
    vle32.v v0, (t4); add s2, t4, t0;
    ^
sgemm.S:83:5: error: instruction requires the following: 'V' (Vector Instructions)
    vle32.v v1, (s2); add s2, s2, t0;

**Comment by mamengjin** [comment]
how to enable the RVV using clang?

the clang was compiled with the https://github.com/isrc-cas/rvv-llvm.git:origin/rvv-iscas

compile command:
mkdir build
cd build
cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/home/mema/usr/local/riscvv09/llvm/ -DCMAKE_BUILD_TYPE="Release" -DLLVM_ENABLE_PROJECTS="clang;lld" -DLLVM_TARGETS_TO_BUILD="RISCV" ../llvm
cmake --build .

cmake --install .

**Comment by xingmingjie** [comment]
Hi @mamengjin . Thanks for reporting the problem. This is because recently we have change the rvv-iscas branch to base on LLVM upstream. So the clang's command option should be `-menable-experimental-extensions -march=rv64gcv0p9`. The `0p9` is used to specify RVV version 0.9.

I have updated Makefile and testcase. You can try it again. Please note that sgemm.S testcase will still be failed for now, we will fix it later.

**Comment by mamengjin** [comment]
Thanks a lot, now everything is OK
