### ISSUE TITLE
关于rvv-benchmark中部分测试用例无法通过的问题

### ISSUE THREAD

**Issue by dockzhong1105** [isrc-cas/rvv-benchmark#2]
各位好，我最近对此仓库下的测试用例进行了测试，我测试的环境如下:

- ubutnu 18.04 64bit
- rvv clang/llvm （rvv-iscas分支）
- riscv-gnu-toolchain（rvv-0.9.x分支） ./configure 时添加了--with-arch=rv64gcv
- spike 最新版本 ./configure时候添加了--with-isa=rv64gcv
- pk最新版本  ./configure 时添加了--with-arch=rv64gcv

之后修改makefile，执行make和make run

在进行测试的时候，我发现有三个用例在执行时会报错，它们分别是：
- saxpy.s 
- sgemm.S
- vvaddint32.s
报错如下：
![image](https://user-images.githubusercontent.com/52490948/98322562-adb18000-2022-11eb-8f5c-36bc86bf7700.png)

**三个用例都会出现“An illegal instruction was executed!”的错误。**

我对其中的vvaddint32.s进行了分析测试：
![image](https://user-images.githubusercontent.com/52490948/98322686-0123ce00-2023-11eb-9fcf-d732ee8e55cd.png)

***在图中用红色圈出的那条指令前，不会报错。一旦执行到这条圈红的指令，就会报错“An illegal instruction was executed!”。***

我想请问大家，是否对这个错误的产生原因有了解？
感激不尽！

**Comment by xingmingjie** [comment]
怀疑是由于spike仓库最新代码已经是rvv 1.0，跟0.9指令编码不兼容导致的。建议切换到较早的commit版本试下：

```
commit 7246912cd7e21f0c68cd3258ae4ab59e4d836155
Merge: 1edd5a0 2469a57
Author: Andrew Waterman <andrew@sifive.com>
Date:   Fri May 29 15:52:45 2020 -0700

    Merge pull request #475 from chihminchao/rvv-0.9
    
    Rvv 0.9
```

**Comment by dockzhong1105** [comment]
> 怀疑是由于spike仓库最新代码已经是rvv 1.0，跟0.9指令编码不兼容导致的。建议切换到较早的commit版本试下：
> 
> ```
> commit 7246912cd7e21f0c68cd3258ae4ab59e4d836155
> Merge: 1edd5a0 2469a57
> Author: Andrew Waterman <andrew@sifive.com>
> Date:   Fri May 29 15:52:45 2020 -0700
> 
>     Merge pull request #475 from chihminchao/rvv-0.9
>     
>     Rvv 0.9
> ```

感谢邢老师，我使用您提供的版本成功通过了另外两个测试。看起来是spike支持的rvv版本的问题了。
但最后一个测试用例，sgemm.s还是会报错“An illegal instruction was executed!”，会不会是因为当前spike版本还存在一定问题呢？

**Comment by xingmingjie** [comment]
最后一个测试用例早前是没有问题的，后来就一直会出错，我们暂时没有查到原因。有可能也是spike版本的问题。

**Comment by dockzhong1105** [comment]
> 最后一个测试用例早前是没有问题的，后来就一直会出错，我们暂时没有查到原因。有可能也是spike版本的问题。

好的，非常感谢您的指导！
